name: Deploy to Remote Server via Docker

on:
  workflow_dispatch: # 手动触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate version.txt
      run: |
        echo "commit: $(git rev-parse HEAD)" > version.txt
        echo "branch: $(git rev-parse --abbrev-ref HEAD)" >> version.txt
        echo "buildTime: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> version.txt

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to server
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_REMOTE_PORT }} ${{ secrets.SSH_REMOTE_USER }}@${{ secrets.SSH_REMOTE_HOST }} "mkdir -p ${{ secrets.SSH_TARGET_DIR }}"
        rsync -avz -e "ssh -p ${{ secrets.SSH_REMOTE_PORT }}" --exclude=node_modules --exclude=.git ./ ${{ secrets.SSH_REMOTE_USER }}@${{ secrets.SSH_REMOTE_HOST }}:${{ secrets.SSH_TARGET_DIR }}

    - name: Generate .env.production on server
      run: |
        ssh -p ${{ secrets.SSH_REMOTE_PORT }} ${{ secrets.SSH_REMOTE_USER }}@${{ secrets.SSH_REMOTE_HOST }} "printf '%s\n' \
          'MONGO_URL=${{ secrets.MONGO_URL }}' \
          'MONGO_POOLMAX=${{ secrets.MONGO_POOLMAX }}' \
          'MONGO_POOLMIN=${{ secrets.MONGO_POOLMIN }}' \
          'PAYMENT_SIGN_KEY=${{ secrets.PAYMENT_SIGN_KEY }}' \
          'PAYMENT_API=${{ secrets.PAYMENT_API }}' \
          'PAYMENT_USERNAME=${{ secrets.PAYMENT_USERNAME }}' \
          'NEXT_PUBLIC_PAYMENT_CHANNELS=${{ secrets.NEXT_PUBLIC_PAYMENT_CHANNELS }}' \
          > ${{ secrets.SSH_TARGET_DIR }}/.env.production"

    - name: Build and Restart Docker container
      run: |
        ssh -p ${{ secrets.SSH_REMOTE_PORT }} ${{ secrets.SSH_REMOTE_USER }}@${{ secrets.SSH_REMOTE_HOST }} << 'EOF'
          cd ${{ secrets.SSH_TARGET_DIR }}
          docker stop ohayoshikin-demo || true
          docker rm ohayoshikin-demo || true
          docker rmi ohayoshikin-demo-img || true
          docker build -t ohayoshikin-demo-img .
          docker run -d \
            --log-driver=json-file \
            --log-opt max-size=3m \
            --log-opt max-file=1 \
            --restart=always \
            --name ohayoshikin-demo \
            --env-file .env.production \
            --network baota_net \
            -p 52005:52005 \
            ohayoshikin-demo-img
        EOF
